module.exports = {
    actions: {
        ARTICLES_FEED_REQUEST: "ARTICLES_FEED_REQUEST",
        ARTICLES_FEED_FAILED: "ARTICLES_FEED_FAILED",
        ARTICLES_FEED_SUCCESS: "ARTICLES_FEED_SUCCESS",
        ARTICLES_FEED_CLEAR:"ARTICLES_FEED_CLEAR",

        AUTH_LOGIN_DIALOG: "AUTH:LOGIN:DIALOG",
        AUTH_LOGIN_REQUEST: "AUTH:LOGIN:REQUEST",
        AUTH_LOGIN_SUCCESS: "AUTH:LOGIN:SUCCESS",
        AUTH_LOGIN_FAILED: "AUTH:LOGIN:FAILED",

        CHANGE_ROUTE: "CHANGE_ROUTE"
    }
};