module.exports = {
    actions: {
        SAVE: "SAVE",

        ARTICLES_FEED_REQUEST: "ARTICLES_FEED_REQUEST",
        ARTICLES_FEED_FAILED: "ARTICLES_FEED_FAILED",
        ARTICLES_FEED_SUCCESS: "ARTICLES_FEED_SUCCESS",
        ARTICLES_FEED_CLEAR:"ARTICLES_FEED_CLEAR",

        AUTH_LOGIN_DIALOG: "AUTH:LOGIN:DIALOG",
        AUTH_LOGIN_REQUEST: "AUTH:LOGIN:REQUEST",
        AUTH_LOGIN_SUCCESS: "AUTH:LOGIN:SUCCESS",
        AUTH_LOGIN_FAILED: "AUTH:LOGIN:FAILED",

        CHANGE_ROUTE: "CHANGE_ROUTE",

        PROFILE_INFO_SUCCESS:"PROFILE_INFO_SUCCESS",
        PROFILE_INFO_FAILED: "PROFILE_INFO_FAILED",
        PROFILE_INFO_REQUEST:"PROFILE_INFO_REQUEST",
        PROFILE_ARTICLES_SUCCESS: "PROFILE_ARTICLES_SUCCESS",
        PROFILE_ARTICLES_FAILED: "PROFILE_ARTICLES_FAILED",
        PROFILE_ARTICLES_REQUEST: "PROFILE_ARTICLES_REQUEST",

        ARTICLE_LOAD_REQUEST: "ARTICLE_LOAD_REQUEST",
        ARTICLE_LOAD_FAILED: "ARTICLE_LOAD_FAILED",
        ARTICLE_LOAD_SUCCESS: "ARTICLE_LOAD_SUCCESS",

        ARTICLE_SAVE_REQUEST:"ARTICLE_SAVE_REQUEST",
        ARTICLE_SAVE_FAILED:"ARTICLE_SAVE_FAILED",
        ARTICLE_SAVE_SUCCESS:"ARTICLE_SAVE_SUCCESS",

        COMMENTS_LOAD_REQUEST: "COMMENTS_LOAD_REQUEST",
        COMMENTS_LOAD_FAILED: "COMMENTS_LOAD_FAILED",
        COMMENTS_LOAD_SUCCESS: "COMMENTS_LOAD_SUCCESS",
        COMMENT_SAVE_REQUEST:"COMMENT_SAVE_REQUEST",
        COMMENT_SAVE_FAILED:"COMMENT_SAVE_FAILED",
        COMMENT_SAVE_SUCCESS:"COMMENT_SAVE_SUCCESS"

    }
};